### ISSUE TITLE
Research Cloud Pak Deployer

### ISSUE THREAD

**Issue by triceam** [cloud-native-toolkit/software-everywhere#258]
https://github.com/IBM/cloud-pak-deployer

Easier Cloud Pak deployments, with aligned versions/dependencies.

https://ibm.github.io/cloud-pak-deployer/advanced/gitops/
https://ibm.github.io/cloud-pak-deployer/advanced/run-on-openshift/

**Comment by triceam** [comment]
This uses olm-utils under the covers to maintain versions/dependencies.

**Comment by balasgit** [comment]
@triceam @seansund 

- Cloud Pak deployer is the asset which was developed originally for project Dapper @Deloitte during my presence last year by IBM Team  Plus i shared information in the our slack 7 months ago.

- They build based on olm-utils which CP4D only supported at this moment

- Currently supported **ONLY CP4D** and other Cloud Pak are not ready to consume at this moment.

- We can discuss if required.

**Slack Thread :** https://ibm-cloudplatform.slack.com/archives/C02KB99P2JC/p1636563623033000

CP Deployer Status as of May 2022

<img width="1233" alt="2022-06-21_17-55-33" src="https://user-images.githubusercontent.com/25986944/174910120-6ba679c3-7341-4ad1-9c28-e3fb9b2dcaa7.png">

**Comment by balasgit** [comment]
Currently they are working to add CP4I as you can see https://github.com/IBM/cloud-pak-deployer/tree/main/automation-roles/50-install-cloud-pak

**Comment by balasgit** [comment]
Summary :
- The Cloud Pak deployer (CP4D) only supports express installation as they are installing all foundation as well as services in the namespace "Foundation_Project"

- Based on our discussion, we needed min specialized install which gets installed across multiple namespace instead of single namespace dumping.. 

Hence this cloud pak deployer may NOT good fit based on current implementation..

**Comment by triceam** [comment]
Implemented: https://github.com/cloud-native-toolkit/terraform-gitops-cp4d-deployer
