### ISSUE TITLE
Update the new module automation process

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/software-everywhere#6]
Currently, the new module process closes the issue once the repository is created. However, it would be good to keep that issue open until the initial release of the module has been made. (We are beginning to enforce the policy that every PR must have an associated issue and reusing the new module request issue would prevent unnecessary duplicates.)

Instead of closing the issue, perhaps we can use `repo_created` and `added_to_catalog` labels to mark the progress.

**Comment by triceam** [comment]
Added a check in `action-repo-issue-extractor` so that it will abort if an issue already has the `repo_created` tag, and will not continue processing.
https://github.com/cloud-native-toolkit/action-repo-issue-extractor/pull/46

Updated workflow in `software-everywhere` so that issues are not closed when a repo is created.   Instead a comment is posted on the issue, and labels are applied.  `repo_created` is added to the issue when the repo is created.  `added_to_catalog` is added when the module is automatically added to the catalog.
https://github.com/cloud-native-toolkit/software-everywhere/pull/76

**Comment by triceam** [comment]
Also updated with a check in `action-repo-issue-extractor` to see if the issue title starts with `Request new module:`.  If it doesn't start with that, it won't be processed. https://github.com/cloud-native-toolkit/action-repo-issue-extractor/pull/47

**Comment by triceam** [comment]
<img width="752" alt="image" src="https://user-images.githubusercontent.com/974294/160750517-aa7ab695-1e96-4f46-a655-b7525d0e3049.png">

**Comment by triceam** [comment]
Moved check to see if its a new module request back into this repo's workflow instead of `action-repo-issue-extractor` https://github.com/cloud-native-toolkit/software-everywhere/pull/80

Also moved check for `repo_creatd` label into this workflow:
https://github.com/cloud-native-toolkit/software-everywhere/pull/81
